- name: Install MicroK8s
  hosts: all
  become: true
  tasks:
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s
      shell: snap install microk8s --classic

    - name: Allow non-root access to MicroK8s
      shell: sudo usermod -aG microk8s $USER

    - name: Configure MicroK8s
      shell: sudo microk8s status --wait-ready

- name: Add nodes to Cluster
  hosts: localhost
  gather_facts: no
  vars:
    target_nodes:
      - pibeta
      - pigamma
  tasks:
    - name: Add individual node to Cluster
      include_tasks: playbooks/add-node.yaml
      with_items: "{{ target_nodes }}"
      vars:
        target_node: "{{ item }}"

