- name: Install MicroK8s
  hosts: all
  become: true
  tasks:
    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s
      shell: snap install microk8s --classic

    - name: Allow non-root access to MicroK8s
      shell: sudo usermod -aG microk8s $USER

    - name: Configure MicroK8s
      shell: sudo microk8s status --wait-ready

- name: Add nodes to Cluster
  hosts: pialpha
  gather_facts: no
  tasks:
    - name: Generate cmd for PiBeta
      shell: microk8s add-node 
      register: join_cluster

    - name: Join PiBeta to cluster
      shell: "{{ join_cluster.stdout | regex_search('microk8s join \\d*\\.\\d*\\.\\d*\\.\\d*:\\d*\\/\\w*\\/\\w*') }}"
      delegate_to: pibeta

    - name: Generate cmd for PiGamma
      shell: microk8s add-node 
      register: join_cluster

    - name: Join PiGamma to cluster
      shell: "{{ join_cluster.stdout | regex_search('microk8s join \\d*\\.\\d*\\.\\d*\\.\\d*:\\d*\\/\\w*\\/\\w*') }}"
      delegate_to: pigamma
